#!/usr/bin/env python3
"""Regenerate the editable galaxy layer using the Python standard library."""

import math
from pathlib import Path
import random

ROOT = Path(__file__).resolve().parents[1]
rng = random.Random(61026)
palette = ("#c3b1ff", "#f1eaff", "#a5bfff")


def project(radius, angle):
    """Two spiral arms, viewed at a gentle tilt like the website's galaxy."""
    x = math.cos(angle) * radius
    y = math.sin(angle) * radius * 0.8
    rotation = -4.55
    return (
        512 + 700 * (x * math.cos(rotation) - y * math.sin(rotation)),
        512 + 700 * (x * math.sin(rotation) + y * math.cos(rotation)),
    )


svg = ['<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">',
       '<!-- Generated by scripts/generate-galaxy-icon.py. macOS supplies the icon shape. -->',
       '<defs><radialGradient id="halo"><stop stop-color="#879ceb" stop-opacity=".4"/>',
       '<stop offset=".45" stop-color="#5867b8" stop-opacity=".1"/>',
       '<stop offset="1" stop-color="#5867b8" stop-opacity="0"/></radialGradient>',
       '<radialGradient id="star"><stop stop-color="#f4f5ff" stop-opacity=".8"/>',
       '<stop offset=".12" stop-color="#e1e7ff" stop-opacity=".55"/>',
       '<stop offset=".4" stop-color="#c4d3ff" stop-opacity=".12"/>',
       '<stop offset="1" stop-color="#c4d3ff" stop-opacity="0"/></radialGradient></defs>',
       '<ellipse cx="512" cy="512" rx="580" ry="470" fill="url(#halo)"/>']

# Wide dust lanes and soft point sprites match the website reference without
# painted orbit lines. All stars and their bloom remain editable vector circles.
for i in range(8500):
    core = i < 650
    diffuse = not core and rng.random() < 0.26
    r = abs(rng.gauss(0, 0.13)) if core else 0.055 + rng.random() ** 0.82 * 1.10
    a = rng.random() * math.tau if core or diffuse else (i % 2) * math.pi + r * 4.6 + rng.gauss(0, 0.045 + r * 0.14)
    x, y = project(r, a)
    bright = rng.random() ** 4
    size = 0.55 + bright * 2.6
    opacity = (0.32 if core or diffuse else 0.6) + bright * 0.4
    color = palette[2 if rng.random() < 0.15 else 0 if rng.random() < 0.6 else 1]
    if bright > 0.12:
        svg.append(f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{size * 5:.2f}" fill="url(#star)" fill-opacity="{opacity:.3f}"/>')
    svg.append(f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{size:.2f}" fill="{color}" fill-opacity="{opacity:.3f}"/>')

for _ in range(240):
    x, y = rng.uniform(0, 1024), rng.uniform(0, 1024)
    svg.append(f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{rng.uniform(.65, 2.1):.2f}" fill="#b8cde6" fill-opacity="{rng.uniform(.2, .65):.3f}"/>')

svg.append('</svg>')
(ROOT / 'AppIcon-Galaxy.icon/Assets/vane-galaxy.svg').write_text('\n'.join(svg) + '\n')
